apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n0naq1kll-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n0naq1kll-java-quarkus-gitops